# Generated by Django 4.2.5 on 2023-10-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='group',
            new_name='name',
        ),
    ]
