# Generated by Django 4.2.5 on 2023-10-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_group', '0002_rename_group_groups_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='GroupChat',
        ),
    ]
